name: Manager Skill CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build image and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install -y maven

    - name: Build file jar
      run: mvn package -DskipTests=true
        
    - name: Login to GitLab registry
      uses: docker/login-action@v1
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t registry.gitlab.com/linhndse130639/manager-skill .
      
    - name: Push Docker image
      run: docker push registry.gitlab.com/linhndse130639/manager-skill

  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            docker stop manager-skill || true
            docker rm manager-skill || true
            docker run -d -p 8080:8080 --name manager-skill registry.gitlab.com/linhndse130639/manager-skill
